language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
cache:
  apt: true
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
sudo: false
env:
- SERVER_IP_ADDRESS=119.29.90.205
addons:
  ssh_known_hosts:
  - 119.29.90.205
script: npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_4c692ed26ecf_key -iv $encrypted_4c692ed26ecf_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@119.29.90.205 pwd
after_success:
  - tar -jcf myblog.tar.bz2 *    # 打包并压缩代码
  - scp myblog.tar.bz2 root@119.29.90.205:/usr/share/nginx/  # 复制到生产服务器上
